import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme";
import { myStore } from "@/store/store";
import { Provider } from "react-redux";
import ReduxProvider from "@/Components/ReduxProvider/ReduxProvider";
import Navbar from "@/Components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/Components/Footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <ReduxProvider>
              <Navbar/>
               {children}
               <Footer/>   
               <Toaster/>
              </ReduxProvider> 
          </ThemeProvider>
        
        </AppRouterCacheProvider>
        
      </body>
    </html>
  );
}
